import 'dotenv/config';
import express from 'express';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import Database from 'better-sqlite3';
import OpenAI from 'openai';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(), PORT=process.env.PORT||3000;
app.set('trust proxy',1);
app.disable('etag');
app.use('/api',(q,s,n)=>{s.set('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');s.set('Pragma','no-cache');s.set('Expires','0');s.set('Vary','Cookie');n()});
fs.mkdirSync(path.join(__dirname,'data'),{recursive:true});fs.mkdirSync(path.join(__dirname,'public','generated'),{recursive:true});
const db=new Database(path.join(__dirname,'data','veyra.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password_hash TEXT,plan TEXT DEFAULT 'free');CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,user_id INTEGER,name TEXT,slug TEXT UNIQUE,prompt TEXT,spec_json TEXT,published INTEGER DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS usage(user_id INTEGER,period TEXT,generations INTEGER DEFAULT 0,images INTEGER DEFAULT 0,PRIMARY KEY(user_id,period));`);
const ai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
app.use('/generated',express.static(path.join(__dirname,'public','generated')));app.use(express.static(path.join(__dirname,'public'),{etag:false,maxAge:0,setHeaders:r=>r.setHeader('Cache-Control','no-store')}));app.use(session({secret:process.env.SESSION_SECRET||'change-this',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:2592000000}}));app.use(express.json({limit:'2mb'}));
const auth=(q,s,n)=>q.session.uid?n():s.status(401).json({error:'Sign in required'});const period=()=>new Date().toISOString().slice(0,7);const limits=p=>p==='pro'?{g:150,i:80,p:5}:p==='starter'?{g:30,i:15,p:1}:{g:3,i:2,p:0};const user=id=>db.prepare('SELECT id,email,plan FROM users WHERE id=?').get(id);function usage(id){db.prepare('INSERT OR IGNORE INTO usage(user_id,period) VALUES(?,?)').run(id,period());return db.prepare('SELECT generations,images FROM usage WHERE user_id=? AND period=?').get(id,period())}const bump=(id,c)=>db.prepare(`UPDATE usage SET ${c}=${c}+1 WHERE user_id=? AND period=?`).run(id,period());
function sessionPayload(q){if(!q.session.uid)return {user:null};let u=user(q.session.uid);if(!u){q.session.uid=null;return {user:null}}return {user:u,usage:usage(u.id),limits:limits(u.plan)}}
function slug(s){let b=String(s||'site').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||'site',x=b,n=1;while(db.prepare('SELECT 1 FROM projects WHERE slug=?').get(x))x=b+'-'+(++n);return x}
app.post('/api/register',async(q,s)=>{let e=String(q.body.email||'').trim().toLowerCase(),p=String(q.body.password||'');if(!e.includes('@')||p.length<8)return s.status(400).json({error:'Use a valid email and a password with at least 8 characters'});try{let existing=db.prepare('SELECT id FROM users WHERE email=?').get(e);if(existing)return s.status(409).json({error:'Account already exists. Sign in instead.'});let h=await bcrypt.hash(p,12),r=db.prepare('INSERT INTO users(email,password_hash) VALUES(?,?)').run(e,h);q.session.uid=Number(r.lastInsertRowid);q.session.save(err=>err?s.status(500).json({error:'Could not start session'}):s.json(sessionPayload(q)))}catch(e){console.error('register',e);s.status(500).json({error:'Could not create account'})}});
app.post('/api/login',async(q,s)=>{let u=db.prepare('SELECT * FROM users WHERE email=?').get(String(q.body.email||'').trim().toLowerCase());if(!u||!await bcrypt.compare(String(q.body.password||''),u.password_hash))return s.status(401).json({error:'Invalid email or password'});q.session.uid=u.id;q.session.save(err=>err?s.status(500).json({error:'Could not start session'}):s.json(sessionPayload(q)))});
app.post('/api/session',(q,s)=>s.json(sessionPayload(q)));app.get('/api/me',(q,s)=>s.json(sessionPayload(q)));app.post('/api/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));
const schema={type:'object',additionalProperties:false,properties:{brand:{type:'string'},title:{type:'string'},direction:{type:'string'},palette:{type:'object',additionalProperties:false,properties:{background:{type:'string'},surface:{type:'string'},text:{type:'string'},muted:{type:'string'},accent:{type:'string'}},required:['background','surface','text','muted','accent']},sections:{type:'array',minItems:5,maxItems:9,items:{type:'object',additionalProperties:false,properties:{type:{type:'string',enum:['hero','features','split','gallery','stats','testimonials','pricing','faq','cta','footer']},eyebrow:{type:'string'},title:{type:'string'},body:{type:'string'},cta:{type:'string'},items:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},body:{type:'string'},meta:{type:'string'}},required:['title','body','meta']}},imageBrief:{type:'string'}},required:['type','eyebrow','title','body','cta','items','imageBrief']}}},required:['brand','title','direction','palette','sections']};
const instructions=`You are Veyra, an elite web design director. Turn the brief into an original premium website system, not a generic AI template. Make strong art-direction choices, concise conversion copy, varied composition and image-led sections. Preserve requested content on revisions. Colors must be valid hex. imageBrief must describe original commercial-safe photography without logos, trademarks or copyrighted characters.`;
async function spec(prompt,current){if(!ai)throw Error('OPENAI_API_KEY is not configured');if(!prompt.trim())throw Error('Describe the website you want to build');let input=current?`CURRENT SITE JSON:\n${JSON.stringify(current)}\n\nCHANGE REQUEST:\n${prompt}\nReturn the complete revised site.`:`CREATE A COMPLETE WEBSITE:\n${prompt}`;let r=await ai.responses.create({model:process.env.OPENAI_TEXT_MODEL||'gpt-5.6-terra',instructions,input,reasoning:{effort:'low'},text:{format:{type:'json_schema',name:'veyra_site',strict:true,schema}}});return JSON.parse(r.output_text)}
async function image(brief,brand){let r=await ai.images.generate({model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2',prompt:`Original premium commercial website photography for ${brand}. ${brief}. No logos, no watermarks, no copyrighted characters. Editorial, art-directed, realistic.`,size:'1536x1024',quality:'medium'}),b=r.data?.[0]?.b64_json;if(!b)return '';let f=Date.now()+'-'+crypto.randomBytes(3).toString('hex')+'.png';fs.writeFileSync(path.join(__dirname,'public','generated',f),Buffer.from(b,'base64'));return '/generated/'+f}
async function addImages(sp,id,max=3){let u=user(id),us=usage(id),left=Math.max(0,limits(u.plan).i-us.images);for(const sec of sp.sections.filter(x=>x.imageBrief).slice(0,Math.min(max,left))){try{sec.imageUrl=await image(sec.imageBrief,sp.brand);if(sec.imageUrl)bump(id,'images')}catch(e){console.error('image generation',e?.message||e);sec.imageUrl=''}}return sp}
app.post('/api/generate',auth,async(q,s)=>{let u=user(q.session.uid),us=usage(u.id);if(us.generations>=limits(u.plan).g)return s.status(402).json({error:'Monthly generation limit reached'});try{let sp=await spec(String(q.body.prompt||''));bump(u.id,'generations');if(q.body.images!==false)sp=await addImages(sp,u.id);let id=crypto.randomUUID(),sl=slug(sp.brand);db.prepare('INSERT INTO projects(id,user_id,name,slug,prompt,spec_json) VALUES(?,?,?,?,?,?)').run(id,u.id,sp.brand,sl,q.body.prompt,JSON.stringify(sp));s.json({project:{id,name:sp.brand,slug:sl,spec:sp,published:false},account:sessionPayload(q)})}catch(e){console.error('generate',e);s.status(500).json({error:e.message||'Generation failed'})}});
app.post('/api/projects/:id/edit',auth,async(q,s)=>{let r=db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(q.params.id,q.session.uid);if(!r)return s.status(404).json({error:'Not found'});let u=user(q.session.uid),us=usage(u.id);if(us.generations>=limits(u.plan).g)return s.status(402).json({error:'Monthly generation limit reached'});try{let sp=await spec(String(q.body.prompt||''),JSON.parse(r.spec_json));bump(q.session.uid,'generations');if(q.body.images)sp=await addImages(sp,q.session.uid,2);db.prepare('UPDATE projects SET spec_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(JSON.stringify(sp),r.id);s.json({project:{id:r.id,name:sp.brand,slug:r.slug,spec:sp,published:!!r.published},account:sessionPayload(q)})}catch(e){console.error('edit',e);s.status(500).json({error:e.message||'Edit failed'})}});
app.get('/api/projects',auth,(q,s)=>s.json({projects:db.prepare('SELECT id,name,slug,published,updated_at FROM projects WHERE user_id=? ORDER BY updated_at DESC').all(q.session.uid)}));app.get('/api/projects/:id',auth,(q,s)=>{let r=db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(q.params.id,q.session.uid);if(!r)return s.status(404).json({error:'Not found'});s.json({project:{id:r.id,name:r.name,slug:r.slug,published:!!r.published,spec:JSON.parse(r.spec_json)}})});
app.post('/api/projects/:id/publish',auth,(q,s)=>{let u=user(q.session.uid),l=limits(u.plan),r=db.prepare('SELECT * FROM projects WHERE id=? AND user_id=?').get(q.params.id,u.id);if(!r)return s.status(404).json({error:'Not found'});if(!l.p)return s.status(402).json({error:'Publishing requires Starter or Pro'});let c=db.prepare('SELECT COUNT(*) c FROM projects WHERE user_id=? AND published=1').get(u.id).c;if(!r.published&&c>=l.p)return s.status(402).json({error:'Published site limit reached'});db.prepare('UPDATE projects SET published=1 WHERE id=?').run(r.id);s.json({url:(process.env.APP_URL||`${q.protocol}://${q.get('host')}`).replace(/\/$/,'')+'/s/'+r.slug})});app.get('/api/public/:slug',(q,s)=>{let r=db.prepare('SELECT spec_json FROM projects WHERE slug=? AND published=1').get(q.params.slug);r?s.json({spec:JSON.parse(r.spec_json)}):s.status(404).json({error:'Not found'})});app.get('/s/:slug',(q,s)=>s.sendFile(path.join(__dirname,'public','site.html')));app.get('/health',(q,s)=>s.json({ok:true,ai:!!ai}));app.listen(PORT,()=>console.log('Veyra on '+PORT));